version: '3.4'

services:
  catalogDb:
   container_name: catalogDb
   restart: always
   ports: 
     - "50000:27017"
   volumes:
     - mongo_data:/data/db 
  catalog.api:
    container_name: catalogApi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogDb:50000"
    depends_on: 
     - catalogDb
    ports:
      - "5000:80"
